# Generated by Django 3.1.1 on 2020-09-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='ExampleModel',
            new_name='PeriodicExampleModel',
        ),
    ]
